AWSTemplateFormatVersion: "2010-09-09"
Description: "Stream logs to the AskEli Platform"

Parameters:
  PrivateKey:
    Type: String
    Description: Please enter your AskEli Private Key
  Version:
    Type: String
    Description: Version of AskEli LogStream
    Default: "1.0.0"

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "askeli-logstream-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: "askeli-logstream-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/askeli-logstream:*"
      Tags:
        - Key: Description
          Value: "Stream logs to the AskEli Platform"
        - Key: Name
          Value: askeli-logstream

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: askeli-logstream
      Description: "Stream logs to the AskEli Platform"
      Handler: bootstrap
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: "askeli-public-cloudformation-templates"
        S3Key: !Sub "aws-logstream/${Version}.zip"
      Runtime: provided.al2023
      Timeout: 10
      Environment:
        Variables:
          PRIVATE_KEY: !Ref PrivateKey

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunction
      Principal: !Sub "logs.${AWS::Region}.amazonaws.com"
      SourceArn: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:*"

  CloudWatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/askeli-logstream"
      RetentionInDays: 3
      Tags:
        - Key: Description
          Value: "Stream logs to the AskEli Platform"
        - Key: Name
          Value: askeli-logstream

Outputs:
  LambdaFunctionArn:
    Description: The ARN of the Lambda function
    Value: !GetAtt LambdaFunction.Arn
